### ISSUE TITLE
No drop() method defined in adapter

### ISSUE THREAD

**Issue by arun057** [appscot/waterline-orientdb#53]
When working with sails.js and setting migrations to drop, lifting the app throws the following error.
```
error: Error (E_UNKNOWN) :: Encountered an unexpected error
: No drop() method defined in adapter!
    at module.exports.drop (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:105:60)
    at drop [as migrateDrop] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:32:8)
    at Query.sync (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:160:25
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:70:7
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/drop.js:36:10
    at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
    at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
    at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:315:18)
    at callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at .../node_modules/waterline-orientdb/lib/connection.js:187:11
    at Object.async.each (.../node_modules/waterline-orientdb/node_modules/async/lib/async.js:121:20)
    at Connection._ensureIndexes (.../node_modules/waterline-orientdb/lib/connection.js:425:9)
    at Db.<anonymous> (.../node_modules/waterline-orientdb/lib/connection.js:177:12)
    at Db.tryCatcher (.../node_modules/waterline-orientdb/node_modules/oriento/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (.../node_modules/waterline-orientdb/node_modules/oriento/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (.../node_modules/waterline-orientdb/node_modules/oriento/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (.../node_modules/waterline-orientdb/node_modules/oriento/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (.../node_modules/waterline-orientdb/node_modules/oriento/node_modules/bluebird/js/main/async.js:79:16)

Details:  Error: No drop() method defined in adapter!
```

**Comment by dmarcelino** [comment]
Hi @arun057, following our [previous discussion (March 2 2015)](https://gitter.im/appscot/waterline-orientdb?at=54f485459622a2fc57f6600b), I haven't been able to reproduce this issue with Sails running with waterline-orientdb. Have you found any new information?

On [March 3 2015](https://gitter.im/appscot/waterline-orientdb?at=54f5bc97b1086da6119e0af2) @jeswinjames24 identified some slowness but drop migration worked for him. #54 should improve the speed of the migration.

**Comment by arun057** [comment]
Hey @dmarcelino still looking into it, I seem to be running into the issue on all of my orms. Closing this issue for now and will reopen if I localize the problem to this repo.

**Comment by dmarcelino** [comment]
Thanks!
